// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ydb/public/api/grpc/ydb_cms_v1.proto

package tech.ydb.cms.v1;

public final class YdbCmsV1 {
  private YdbCmsV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$ydb/public/api/grpc/ydb_cms_v1.proto\022\n" +
      "Ydb.Cms.V1\032#ydb/public/api/protos/ydb_cm" +
      "s.proto2\234\004\n\nCmsService\022Q\n\016CreateDatabase" +
      "\022\036.Ydb.Cms.CreateDatabaseRequest\032\037.Ydb.C" +
      "ms.CreateDatabaseResponse\022Z\n\021GetDatabase" +
      "Status\022!.Ydb.Cms.GetDatabaseStatusReques" +
      "t\032\".Ydb.Cms.GetDatabaseStatusResponse\022N\n" +
      "\rAlterDatabase\022\035.Ydb.Cms.AlterDatabaseRe" +
      "quest\032\036.Ydb.Cms.AlterDatabaseResponse\022N\n" +
      "\rListDatabases\022\035.Ydb.Cms.ListDatabasesRe" +
      "quest\032\036.Ydb.Cms.ListDatabasesResponse\022Q\n" +
      "\016RemoveDatabase\022\036.Ydb.Cms.RemoveDatabase" +
      "Request\032\037.Ydb.Cms.RemoveDatabaseResponse" +
      "\022l\n\027DescribeDatabaseOptions\022\'.Ydb.Cms.De" +
      "scribeDatabaseOptionsRequest\032(.Ydb.Cms.D" +
      "escribeDatabaseOptionsResponseB\027\n\025com.ya" +
      "ndex.ydb.cms.v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tech.ydb.cms.YdbCms.getDescriptor(),
        });
    tech.ydb.cms.YdbCms.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
