// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ydb/public/api/grpc/ydb_discovery_v1.proto

package tech.ydb.discovery.v1;

public final class YdbDiscoveryV1 {
  private YdbDiscoveryV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*ydb/public/api/grpc/ydb_discovery_v1.p" +
      "roto\022\020Ydb.Discovery.V1\032)ydb/public/api/p" +
      "rotos/ydb_discovery.proto2\265\001\n\020DiscoveryS" +
      "ervice\022Z\n\rListEndpoints\022#.Ydb.Discovery." +
      "ListEndpointsRequest\032$.Ydb.Discovery.Lis" +
      "tEndpointsResponse\022E\n\006WhoAmI\022\034.Ydb.Disco" +
      "very.WhoAmIRequest\032\035.Ydb.Discovery.WhoAm" +
      "IResponseB\035\n\033tech.ydb.discovery.v1" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tech.ydb.discovery.DiscoveryProtos.getDescriptor(),
        });
    tech.ydb.discovery.DiscoveryProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
