// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kikimr/public/api/grpc/draft/ydb_persqueue_v1.proto

package tech.ydb.persqueue.v1;

public final class YdbPersqueueV1 {
  private YdbPersqueueV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3kikimr/public/api/grpc/draft/ydb_persq" +
      "ueue_v1.proto\022\020Ydb.PersQueue.V1\032/kikimr/" +
      "public/api/protos/ydb_persqueue_v1.proto" +
      "2\255\002\n\020PersQueueService\022a\n\022CreateWriteSess" +
      "ion\022\".Ydb.PersQueue.WriteSessionRequest\032" +
      "#.Ydb.PersQueue.WriteSessionResponse(\0010\001" +
      "\022^\n\021CreateReadSession\022!.Ydb.PersQueue.Re" +
      "adSessionRequest\032\".Ydb.PersQueue.ReadSes" +
      "sionResponse(\0010\001\022V\n\023GetReadSessionsInfo\022" +
      "\036.Ydb.PersQueue.ReadInfoRequest\032\037.Ydb.Pe",
      "rsQueue.ReadInfoResponseB\035\n\033com.yandex.y" +
      "db.persqueue.v1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tech.ydb.persqueue.YdbPersqueueV1.getDescriptor(),
        }, assigner);
    tech.ydb.persqueue.YdbPersqueueV1.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
