// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kikimr/public/api/grpc/draft/streaming_v1.proto

package com.yandex.streaming.v1;

public final class StreamingV1 {
  private StreamingV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/kikimr/public/api/grpc/draft/streaming" +
      "_v1.proto\022\014Streaming.V1\032.kikimr/public/a" +
      "pi/protos/draft/streaming.proto2\323\002\n\020Stre" +
      "amingService\022O\n\014InstallQuery\022\036.Streaming" +
      ".InstallQueryRequest\032\037.Streaming.Install" +
      "QueryResponse\022L\n\013DeleteQuery\022\035.Streaming" +
      ".DeleteQueryRequest\032\036.Streaming.DeleteQu" +
      "eryResponse\022L\n\013ListQueries\022\035.Streaming.L" +
      "istQueriesRequest\032\036.Streaming.ListQuerie" +
      "sResponse\022R\n\rDescribeQuery\022\037.Streaming.D" +
      "escribeQueryRequest\032 .Streaming.Describe" +
      "QueryResponseB\031\n\027com.yandex.streaming.v1" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yandex.Streaming.StreamingProtos.getDescriptor(),
        });
    com.yandex.Streaming.StreamingProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
