// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kikimr/public/api/grpc/draft/streaming_v1.proto

package com.yandex.streaming.v1;

public final class StreamingV1 {
  private StreamingV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/kikimr/public/api/grpc/draft/streaming" +
      "_v1.proto\022\014Streaming.V1\032.kikimr/public/a" +
      "pi/protos/draft/streaming.proto2c\n\020Strea" +
      "mingService\022O\n\014ExecuteQuery\022\036.Streaming." +
      "ExecuteQueryRequest\032\037.Streaming.ExecuteQ" +
      "ueryResponseB\031\n\027com.yandex.streaming.v1b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yandex.Streaming.StreamingProtos.getDescriptor(),
        }, assigner);
    com.yandex.Streaming.StreamingProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
