// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kikimr/public/api/grpc/ydb_backup_v1.proto

package tech.ydb.backup.v1;

public final class YdbBackupV1 {
  private YdbBackupV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*kikimr/public/api/grpc/ydb_backup_v1.p" +
      "roto\022\rYdb.Backup.V1\032)kikimr/public/api/p" +
      "rotos/ydb_backup.proto2b\n\rBackupService\022" +
      "Q\n\014CreateBackup\022\037.Ydb.Backup.CreateBacku" +
      "pRequest\032 .Ydb.Backup.CreateBackupRespon" +
      "seB\032\n\030tech.ydb.backup.v1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tech.ydb.backup.YdbBackup.getDescriptor(),
        }, assigner);
    tech.ydb.backup.YdbBackup.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
