// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kikimr/public/api/protos/ydb_issue_message.proto

package tech.ydb;

public final class YdbIssueMessage {
  private YdbIssueMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IssueMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Ydb.Issue.IssueMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Ydb.Issue.IssueMessage.Position position = 1;</code>
     * @return Whether the position field is set.
     */
    boolean hasPosition();
    /**
     * <code>optional .Ydb.Issue.IssueMessage.Position position = 1;</code>
     * @return The position.
     */
    tech.ydb.YdbIssueMessage.IssueMessage.Position getPosition();
    /**
     * <code>optional .Ydb.Issue.IssueMessage.Position position = 1;</code>
     */
    tech.ydb.YdbIssueMessage.IssueMessage.PositionOrBuilder getPositionOrBuilder();

    /**
     * <code>optional string message = 2;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>optional .Ydb.Issue.IssueMessage.Position end_position = 3;</code>
     * @return Whether the endPosition field is set.
     */
    boolean hasEndPosition();
    /**
     * <code>optional .Ydb.Issue.IssueMessage.Position end_position = 3;</code>
     * @return The endPosition.
     */
    tech.ydb.YdbIssueMessage.IssueMessage.Position getEndPosition();
    /**
     * <code>optional .Ydb.Issue.IssueMessage.Position end_position = 3;</code>
     */
    tech.ydb.YdbIssueMessage.IssueMessage.PositionOrBuilder getEndPositionOrBuilder();

    /**
     * <code>optional uint32 issue_code = 4;</code>
     * @return Whether the issueCode field is set.
     */
    boolean hasIssueCode();
    /**
     * <code>optional uint32 issue_code = 4;</code>
     * @return The issueCode.
     */
    int getIssueCode();

    /**
     * <pre>
     * Severity values from yql/public/issue/protos/issue_severity.proto
     * FATAL = 0;
     * ERROR = 1;
     * WARNING = 2;
     * INFO = 3;
     * </pre>
     *
     * <code>optional uint32 severity = 5;</code>
     * @return Whether the severity field is set.
     */
    boolean hasSeverity();
    /**
     * <pre>
     * Severity values from yql/public/issue/protos/issue_severity.proto
     * FATAL = 0;
     * ERROR = 1;
     * WARNING = 2;
     * INFO = 3;
     * </pre>
     *
     * <code>optional uint32 severity = 5;</code>
     * @return The severity.
     */
    int getSeverity();

    /**
     * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
     */
    java.util.List<tech.ydb.YdbIssueMessage.IssueMessage> 
        getIssuesList();
    /**
     * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
     */
    tech.ydb.YdbIssueMessage.IssueMessage getIssues(int index);
    /**
     * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
     */
    int getIssuesCount();
    /**
     * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
     */
    java.util.List<? extends tech.ydb.YdbIssueMessage.IssueMessageOrBuilder> 
        getIssuesOrBuilderList();
    /**
     * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
     */
    tech.ydb.YdbIssueMessage.IssueMessageOrBuilder getIssuesOrBuilder(
        int index);
  }
  /**
   * <pre>
   * IssueMessage is a transport format for yql/public/issue library
   * </pre>
   *
   * Protobuf type {@code Ydb.Issue.IssueMessage}
   */
  public static final class IssueMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Ydb.Issue.IssueMessage)
      IssueMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IssueMessage.newBuilder() to construct.
    private IssueMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IssueMessage() {
      message_ = "";
      issues_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IssueMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IssueMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tech.ydb.YdbIssueMessage.IssueMessage.Position.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = position_.toBuilder();
              }
              position_ = input.readMessage(tech.ydb.YdbIssueMessage.IssueMessage.Position.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(position_);
                position_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              message_ = bs;
              break;
            }
            case 26: {
              tech.ydb.YdbIssueMessage.IssueMessage.Position.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = endPosition_.toBuilder();
              }
              endPosition_ = input.readMessage(tech.ydb.YdbIssueMessage.IssueMessage.Position.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(endPosition_);
                endPosition_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              issueCode_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              severity_ = input.readUInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) != 0)) {
                issues_ = new java.util.ArrayList<tech.ydb.YdbIssueMessage.IssueMessage>();
                mutable_bitField0_ |= 0x00000020;
              }
              issues_.add(
                  input.readMessage(tech.ydb.YdbIssueMessage.IssueMessage.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) != 0)) {
          issues_ = java.util.Collections.unmodifiableList(issues_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.ydb.YdbIssueMessage.internal_static_Ydb_Issue_IssueMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.ydb.YdbIssueMessage.internal_static_Ydb_Issue_IssueMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.ydb.YdbIssueMessage.IssueMessage.class, tech.ydb.YdbIssueMessage.IssueMessage.Builder.class);
    }

    public interface PositionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Ydb.Issue.IssueMessage.Position)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional uint32 row = 1;</code>
       * @return Whether the row field is set.
       */
      boolean hasRow();
      /**
       * <code>optional uint32 row = 1;</code>
       * @return The row.
       */
      int getRow();

      /**
       * <code>optional uint32 column = 2;</code>
       * @return Whether the column field is set.
       */
      boolean hasColumn();
      /**
       * <code>optional uint32 column = 2;</code>
       * @return The column.
       */
      int getColumn();

      /**
       * <code>optional string file = 3;</code>
       * @return Whether the file field is set.
       */
      boolean hasFile();
      /**
       * <code>optional string file = 3;</code>
       * @return The file.
       */
      java.lang.String getFile();
      /**
       * <code>optional string file = 3;</code>
       * @return The bytes for file.
       */
      com.google.protobuf.ByteString
          getFileBytes();
    }
    /**
     * Protobuf type {@code Ydb.Issue.IssueMessage.Position}
     */
    public static final class Position extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Ydb.Issue.IssueMessage.Position)
        PositionOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Position.newBuilder() to construct.
      private Position(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Position() {
        file_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Position();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Position(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bitField0_ |= 0x00000001;
                row_ = input.readUInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                column_ = input.readUInt32();
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                file_ = bs;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tech.ydb.YdbIssueMessage.internal_static_Ydb_Issue_IssueMessage_Position_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tech.ydb.YdbIssueMessage.internal_static_Ydb_Issue_IssueMessage_Position_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tech.ydb.YdbIssueMessage.IssueMessage.Position.class, tech.ydb.YdbIssueMessage.IssueMessage.Position.Builder.class);
      }

      private int bitField0_;
      public static final int ROW_FIELD_NUMBER = 1;
      private int row_;
      /**
       * <code>optional uint32 row = 1;</code>
       * @return Whether the row field is set.
       */
      @java.lang.Override
      public boolean hasRow() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 row = 1;</code>
       * @return The row.
       */
      @java.lang.Override
      public int getRow() {
        return row_;
      }

      public static final int COLUMN_FIELD_NUMBER = 2;
      private int column_;
      /**
       * <code>optional uint32 column = 2;</code>
       * @return Whether the column field is set.
       */
      @java.lang.Override
      public boolean hasColumn() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint32 column = 2;</code>
       * @return The column.
       */
      @java.lang.Override
      public int getColumn() {
        return column_;
      }

      public static final int FILE_FIELD_NUMBER = 3;
      private volatile java.lang.Object file_;
      /**
       * <code>optional string file = 3;</code>
       * @return Whether the file field is set.
       */
      @java.lang.Override
      public boolean hasFile() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string file = 3;</code>
       * @return The file.
       */
      @java.lang.Override
      public java.lang.String getFile() {
        java.lang.Object ref = file_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            file_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string file = 3;</code>
       * @return The bytes for file.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFileBytes() {
        java.lang.Object ref = file_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          file_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeUInt32(1, row_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeUInt32(2, column_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, file_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, row_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, column_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, file_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof tech.ydb.YdbIssueMessage.IssueMessage.Position)) {
          return super.equals(obj);
        }
        tech.ydb.YdbIssueMessage.IssueMessage.Position other = (tech.ydb.YdbIssueMessage.IssueMessage.Position) obj;

        if (hasRow() != other.hasRow()) return false;
        if (hasRow()) {
          if (getRow()
              != other.getRow()) return false;
        }
        if (hasColumn() != other.hasColumn()) return false;
        if (hasColumn()) {
          if (getColumn()
              != other.getColumn()) return false;
        }
        if (hasFile() != other.hasFile()) return false;
        if (hasFile()) {
          if (!getFile()
              .equals(other.getFile())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasRow()) {
          hash = (37 * hash) + ROW_FIELD_NUMBER;
          hash = (53 * hash) + getRow();
        }
        if (hasColumn()) {
          hash = (37 * hash) + COLUMN_FIELD_NUMBER;
          hash = (53 * hash) + getColumn();
        }
        if (hasFile()) {
          hash = (37 * hash) + FILE_FIELD_NUMBER;
          hash = (53 * hash) + getFile().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static tech.ydb.YdbIssueMessage.IssueMessage.Position parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static tech.ydb.YdbIssueMessage.IssueMessage.Position parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static tech.ydb.YdbIssueMessage.IssueMessage.Position parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static tech.ydb.YdbIssueMessage.IssueMessage.Position parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static tech.ydb.YdbIssueMessage.IssueMessage.Position parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static tech.ydb.YdbIssueMessage.IssueMessage.Position parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static tech.ydb.YdbIssueMessage.IssueMessage.Position parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static tech.ydb.YdbIssueMessage.IssueMessage.Position parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static tech.ydb.YdbIssueMessage.IssueMessage.Position parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static tech.ydb.YdbIssueMessage.IssueMessage.Position parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static tech.ydb.YdbIssueMessage.IssueMessage.Position parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static tech.ydb.YdbIssueMessage.IssueMessage.Position parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(tech.ydb.YdbIssueMessage.IssueMessage.Position prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Ydb.Issue.IssueMessage.Position}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Ydb.Issue.IssueMessage.Position)
          tech.ydb.YdbIssueMessage.IssueMessage.PositionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return tech.ydb.YdbIssueMessage.internal_static_Ydb_Issue_IssueMessage_Position_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return tech.ydb.YdbIssueMessage.internal_static_Ydb_Issue_IssueMessage_Position_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  tech.ydb.YdbIssueMessage.IssueMessage.Position.class, tech.ydb.YdbIssueMessage.IssueMessage.Position.Builder.class);
        }

        // Construct using tech.ydb.YdbIssueMessage.IssueMessage.Position.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          row_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          column_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          file_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return tech.ydb.YdbIssueMessage.internal_static_Ydb_Issue_IssueMessage_Position_descriptor;
        }

        @java.lang.Override
        public tech.ydb.YdbIssueMessage.IssueMessage.Position getDefaultInstanceForType() {
          return tech.ydb.YdbIssueMessage.IssueMessage.Position.getDefaultInstance();
        }

        @java.lang.Override
        public tech.ydb.YdbIssueMessage.IssueMessage.Position build() {
          tech.ydb.YdbIssueMessage.IssueMessage.Position result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public tech.ydb.YdbIssueMessage.IssueMessage.Position buildPartial() {
          tech.ydb.YdbIssueMessage.IssueMessage.Position result = new tech.ydb.YdbIssueMessage.IssueMessage.Position(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.row_ = row_;
            to_bitField0_ |= 0x00000001;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.column_ = column_;
            to_bitField0_ |= 0x00000002;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            to_bitField0_ |= 0x00000004;
          }
          result.file_ = file_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof tech.ydb.YdbIssueMessage.IssueMessage.Position) {
            return mergeFrom((tech.ydb.YdbIssueMessage.IssueMessage.Position)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(tech.ydb.YdbIssueMessage.IssueMessage.Position other) {
          if (other == tech.ydb.YdbIssueMessage.IssueMessage.Position.getDefaultInstance()) return this;
          if (other.hasRow()) {
            setRow(other.getRow());
          }
          if (other.hasColumn()) {
            setColumn(other.getColumn());
          }
          if (other.hasFile()) {
            bitField0_ |= 0x00000004;
            file_ = other.file_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          tech.ydb.YdbIssueMessage.IssueMessage.Position parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (tech.ydb.YdbIssueMessage.IssueMessage.Position) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int row_ ;
        /**
         * <code>optional uint32 row = 1;</code>
         * @return Whether the row field is set.
         */
        @java.lang.Override
        public boolean hasRow() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional uint32 row = 1;</code>
         * @return The row.
         */
        @java.lang.Override
        public int getRow() {
          return row_;
        }
        /**
         * <code>optional uint32 row = 1;</code>
         * @param value The row to set.
         * @return This builder for chaining.
         */
        public Builder setRow(int value) {
          bitField0_ |= 0x00000001;
          row_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 row = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearRow() {
          bitField0_ = (bitField0_ & ~0x00000001);
          row_ = 0;
          onChanged();
          return this;
        }

        private int column_ ;
        /**
         * <code>optional uint32 column = 2;</code>
         * @return Whether the column field is set.
         */
        @java.lang.Override
        public boolean hasColumn() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional uint32 column = 2;</code>
         * @return The column.
         */
        @java.lang.Override
        public int getColumn() {
          return column_;
        }
        /**
         * <code>optional uint32 column = 2;</code>
         * @param value The column to set.
         * @return This builder for chaining.
         */
        public Builder setColumn(int value) {
          bitField0_ |= 0x00000002;
          column_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 column = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearColumn() {
          bitField0_ = (bitField0_ & ~0x00000002);
          column_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object file_ = "";
        /**
         * <code>optional string file = 3;</code>
         * @return Whether the file field is set.
         */
        public boolean hasFile() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>optional string file = 3;</code>
         * @return The file.
         */
        public java.lang.String getFile() {
          java.lang.Object ref = file_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              file_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string file = 3;</code>
         * @return The bytes for file.
         */
        public com.google.protobuf.ByteString
            getFileBytes() {
          java.lang.Object ref = file_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            file_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string file = 3;</code>
         * @param value The file to set.
         * @return This builder for chaining.
         */
        public Builder setFile(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          file_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string file = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearFile() {
          bitField0_ = (bitField0_ & ~0x00000004);
          file_ = getDefaultInstance().getFile();
          onChanged();
          return this;
        }
        /**
         * <code>optional string file = 3;</code>
         * @param value The bytes for file to set.
         * @return This builder for chaining.
         */
        public Builder setFileBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          file_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Ydb.Issue.IssueMessage.Position)
      }

      // @@protoc_insertion_point(class_scope:Ydb.Issue.IssueMessage.Position)
      private static final tech.ydb.YdbIssueMessage.IssueMessage.Position DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new tech.ydb.YdbIssueMessage.IssueMessage.Position();
      }

      public static tech.ydb.YdbIssueMessage.IssueMessage.Position getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Position>
          PARSER = new com.google.protobuf.AbstractParser<Position>() {
        @java.lang.Override
        public Position parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Position(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Position> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Position> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public tech.ydb.YdbIssueMessage.IssueMessage.Position getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int POSITION_FIELD_NUMBER = 1;
    private tech.ydb.YdbIssueMessage.IssueMessage.Position position_;
    /**
     * <code>optional .Ydb.Issue.IssueMessage.Position position = 1;</code>
     * @return Whether the position field is set.
     */
    @java.lang.Override
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .Ydb.Issue.IssueMessage.Position position = 1;</code>
     * @return The position.
     */
    @java.lang.Override
    public tech.ydb.YdbIssueMessage.IssueMessage.Position getPosition() {
      return position_ == null ? tech.ydb.YdbIssueMessage.IssueMessage.Position.getDefaultInstance() : position_;
    }
    /**
     * <code>optional .Ydb.Issue.IssueMessage.Position position = 1;</code>
     */
    @java.lang.Override
    public tech.ydb.YdbIssueMessage.IssueMessage.PositionOrBuilder getPositionOrBuilder() {
      return position_ == null ? tech.ydb.YdbIssueMessage.IssueMessage.Position.getDefaultInstance() : position_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>optional string message = 2;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int END_POSITION_FIELD_NUMBER = 3;
    private tech.ydb.YdbIssueMessage.IssueMessage.Position endPosition_;
    /**
     * <code>optional .Ydb.Issue.IssueMessage.Position end_position = 3;</code>
     * @return Whether the endPosition field is set.
     */
    @java.lang.Override
    public boolean hasEndPosition() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .Ydb.Issue.IssueMessage.Position end_position = 3;</code>
     * @return The endPosition.
     */
    @java.lang.Override
    public tech.ydb.YdbIssueMessage.IssueMessage.Position getEndPosition() {
      return endPosition_ == null ? tech.ydb.YdbIssueMessage.IssueMessage.Position.getDefaultInstance() : endPosition_;
    }
    /**
     * <code>optional .Ydb.Issue.IssueMessage.Position end_position = 3;</code>
     */
    @java.lang.Override
    public tech.ydb.YdbIssueMessage.IssueMessage.PositionOrBuilder getEndPositionOrBuilder() {
      return endPosition_ == null ? tech.ydb.YdbIssueMessage.IssueMessage.Position.getDefaultInstance() : endPosition_;
    }

    public static final int ISSUE_CODE_FIELD_NUMBER = 4;
    private int issueCode_;
    /**
     * <code>optional uint32 issue_code = 4;</code>
     * @return Whether the issueCode field is set.
     */
    @java.lang.Override
    public boolean hasIssueCode() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint32 issue_code = 4;</code>
     * @return The issueCode.
     */
    @java.lang.Override
    public int getIssueCode() {
      return issueCode_;
    }

    public static final int SEVERITY_FIELD_NUMBER = 5;
    private int severity_;
    /**
     * <pre>
     * Severity values from yql/public/issue/protos/issue_severity.proto
     * FATAL = 0;
     * ERROR = 1;
     * WARNING = 2;
     * INFO = 3;
     * </pre>
     *
     * <code>optional uint32 severity = 5;</code>
     * @return Whether the severity field is set.
     */
    @java.lang.Override
    public boolean hasSeverity() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Severity values from yql/public/issue/protos/issue_severity.proto
     * FATAL = 0;
     * ERROR = 1;
     * WARNING = 2;
     * INFO = 3;
     * </pre>
     *
     * <code>optional uint32 severity = 5;</code>
     * @return The severity.
     */
    @java.lang.Override
    public int getSeverity() {
      return severity_;
    }

    public static final int ISSUES_FIELD_NUMBER = 6;
    private java.util.List<tech.ydb.YdbIssueMessage.IssueMessage> issues_;
    /**
     * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
     */
    @java.lang.Override
    public java.util.List<tech.ydb.YdbIssueMessage.IssueMessage> getIssuesList() {
      return issues_;
    }
    /**
     * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
     */
    @java.lang.Override
    public java.util.List<? extends tech.ydb.YdbIssueMessage.IssueMessageOrBuilder> 
        getIssuesOrBuilderList() {
      return issues_;
    }
    /**
     * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
     */
    @java.lang.Override
    public int getIssuesCount() {
      return issues_.size();
    }
    /**
     * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
     */
    @java.lang.Override
    public tech.ydb.YdbIssueMessage.IssueMessage getIssues(int index) {
      return issues_.get(index);
    }
    /**
     * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
     */
    @java.lang.Override
    public tech.ydb.YdbIssueMessage.IssueMessageOrBuilder getIssuesOrBuilder(
        int index) {
      return issues_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getPosition());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getEndPosition());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt32(4, issueCode_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt32(5, severity_);
      }
      for (int i = 0; i < issues_.size(); i++) {
        output.writeMessage(6, issues_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPosition());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getEndPosition());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, issueCode_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, severity_);
      }
      for (int i = 0; i < issues_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, issues_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tech.ydb.YdbIssueMessage.IssueMessage)) {
        return super.equals(obj);
      }
      tech.ydb.YdbIssueMessage.IssueMessage other = (tech.ydb.YdbIssueMessage.IssueMessage) obj;

      if (hasPosition() != other.hasPosition()) return false;
      if (hasPosition()) {
        if (!getPosition()
            .equals(other.getPosition())) return false;
      }
      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage()
            .equals(other.getMessage())) return false;
      }
      if (hasEndPosition() != other.hasEndPosition()) return false;
      if (hasEndPosition()) {
        if (!getEndPosition()
            .equals(other.getEndPosition())) return false;
      }
      if (hasIssueCode() != other.hasIssueCode()) return false;
      if (hasIssueCode()) {
        if (getIssueCode()
            != other.getIssueCode()) return false;
      }
      if (hasSeverity() != other.hasSeverity()) return false;
      if (hasSeverity()) {
        if (getSeverity()
            != other.getSeverity()) return false;
      }
      if (!getIssuesList()
          .equals(other.getIssuesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPosition()) {
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getPosition().hashCode();
      }
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      if (hasEndPosition()) {
        hash = (37 * hash) + END_POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getEndPosition().hashCode();
      }
      if (hasIssueCode()) {
        hash = (37 * hash) + ISSUE_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getIssueCode();
      }
      if (hasSeverity()) {
        hash = (37 * hash) + SEVERITY_FIELD_NUMBER;
        hash = (53 * hash) + getSeverity();
      }
      if (getIssuesCount() > 0) {
        hash = (37 * hash) + ISSUES_FIELD_NUMBER;
        hash = (53 * hash) + getIssuesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tech.ydb.YdbIssueMessage.IssueMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tech.ydb.YdbIssueMessage.IssueMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tech.ydb.YdbIssueMessage.IssueMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tech.ydb.YdbIssueMessage.IssueMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tech.ydb.YdbIssueMessage.IssueMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tech.ydb.YdbIssueMessage.IssueMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tech.ydb.YdbIssueMessage.IssueMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tech.ydb.YdbIssueMessage.IssueMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tech.ydb.YdbIssueMessage.IssueMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tech.ydb.YdbIssueMessage.IssueMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tech.ydb.YdbIssueMessage.IssueMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tech.ydb.YdbIssueMessage.IssueMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tech.ydb.YdbIssueMessage.IssueMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * IssueMessage is a transport format for yql/public/issue library
     * </pre>
     *
     * Protobuf type {@code Ydb.Issue.IssueMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Ydb.Issue.IssueMessage)
        tech.ydb.YdbIssueMessage.IssueMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tech.ydb.YdbIssueMessage.internal_static_Ydb_Issue_IssueMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tech.ydb.YdbIssueMessage.internal_static_Ydb_Issue_IssueMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tech.ydb.YdbIssueMessage.IssueMessage.class, tech.ydb.YdbIssueMessage.IssueMessage.Builder.class);
      }

      // Construct using tech.ydb.YdbIssueMessage.IssueMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPositionFieldBuilder();
          getEndPositionFieldBuilder();
          getIssuesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (positionBuilder_ == null) {
          position_ = null;
        } else {
          positionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (endPositionBuilder_ == null) {
          endPosition_ = null;
        } else {
          endPositionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        issueCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        severity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (issuesBuilder_ == null) {
          issues_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          issuesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tech.ydb.YdbIssueMessage.internal_static_Ydb_Issue_IssueMessage_descriptor;
      }

      @java.lang.Override
      public tech.ydb.YdbIssueMessage.IssueMessage getDefaultInstanceForType() {
        return tech.ydb.YdbIssueMessage.IssueMessage.getDefaultInstance();
      }

      @java.lang.Override
      public tech.ydb.YdbIssueMessage.IssueMessage build() {
        tech.ydb.YdbIssueMessage.IssueMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tech.ydb.YdbIssueMessage.IssueMessage buildPartial() {
        tech.ydb.YdbIssueMessage.IssueMessage result = new tech.ydb.YdbIssueMessage.IssueMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (positionBuilder_ == null) {
            result.position_ = position_;
          } else {
            result.position_ = positionBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (endPositionBuilder_ == null) {
            result.endPosition_ = endPosition_;
          } else {
            result.endPosition_ = endPositionBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.issueCode_ = issueCode_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.severity_ = severity_;
          to_bitField0_ |= 0x00000010;
        }
        if (issuesBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0)) {
            issues_ = java.util.Collections.unmodifiableList(issues_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.issues_ = issues_;
        } else {
          result.issues_ = issuesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tech.ydb.YdbIssueMessage.IssueMessage) {
          return mergeFrom((tech.ydb.YdbIssueMessage.IssueMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tech.ydb.YdbIssueMessage.IssueMessage other) {
        if (other == tech.ydb.YdbIssueMessage.IssueMessage.getDefaultInstance()) return this;
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000002;
          message_ = other.message_;
          onChanged();
        }
        if (other.hasEndPosition()) {
          mergeEndPosition(other.getEndPosition());
        }
        if (other.hasIssueCode()) {
          setIssueCode(other.getIssueCode());
        }
        if (other.hasSeverity()) {
          setSeverity(other.getSeverity());
        }
        if (issuesBuilder_ == null) {
          if (!other.issues_.isEmpty()) {
            if (issues_.isEmpty()) {
              issues_ = other.issues_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureIssuesIsMutable();
              issues_.addAll(other.issues_);
            }
            onChanged();
          }
        } else {
          if (!other.issues_.isEmpty()) {
            if (issuesBuilder_.isEmpty()) {
              issuesBuilder_.dispose();
              issuesBuilder_ = null;
              issues_ = other.issues_;
              bitField0_ = (bitField0_ & ~0x00000020);
              issuesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getIssuesFieldBuilder() : null;
            } else {
              issuesBuilder_.addAllMessages(other.issues_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tech.ydb.YdbIssueMessage.IssueMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tech.ydb.YdbIssueMessage.IssueMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private tech.ydb.YdbIssueMessage.IssueMessage.Position position_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ydb.YdbIssueMessage.IssueMessage.Position, tech.ydb.YdbIssueMessage.IssueMessage.Position.Builder, tech.ydb.YdbIssueMessage.IssueMessage.PositionOrBuilder> positionBuilder_;
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position position = 1;</code>
       * @return Whether the position field is set.
       */
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position position = 1;</code>
       * @return The position.
       */
      public tech.ydb.YdbIssueMessage.IssueMessage.Position getPosition() {
        if (positionBuilder_ == null) {
          return position_ == null ? tech.ydb.YdbIssueMessage.IssueMessage.Position.getDefaultInstance() : position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position position = 1;</code>
       */
      public Builder setPosition(tech.ydb.YdbIssueMessage.IssueMessage.Position value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
          onChanged();
        } else {
          positionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position position = 1;</code>
       */
      public Builder setPosition(
          tech.ydb.YdbIssueMessage.IssueMessage.Position.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
          onChanged();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position position = 1;</code>
       */
      public Builder mergePosition(tech.ydb.YdbIssueMessage.IssueMessage.Position value) {
        if (positionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              position_ != null &&
              position_ != tech.ydb.YdbIssueMessage.IssueMessage.Position.getDefaultInstance()) {
            position_ =
              tech.ydb.YdbIssueMessage.IssueMessage.Position.newBuilder(position_).mergeFrom(value).buildPartial();
          } else {
            position_ = value;
          }
          onChanged();
        } else {
          positionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position position = 1;</code>
       */
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = null;
          onChanged();
        } else {
          positionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position position = 1;</code>
       */
      public tech.ydb.YdbIssueMessage.IssueMessage.Position.Builder getPositionBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position position = 1;</code>
       */
      public tech.ydb.YdbIssueMessage.IssueMessage.PositionOrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_ == null ?
              tech.ydb.YdbIssueMessage.IssueMessage.Position.getDefaultInstance() : position_;
        }
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position position = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ydb.YdbIssueMessage.IssueMessage.Position, tech.ydb.YdbIssueMessage.IssueMessage.Position.Builder, tech.ydb.YdbIssueMessage.IssueMessage.PositionOrBuilder> 
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tech.ydb.YdbIssueMessage.IssueMessage.Position, tech.ydb.YdbIssueMessage.IssueMessage.Position.Builder, tech.ydb.YdbIssueMessage.IssueMessage.PositionOrBuilder>(
                  getPosition(),
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 2;</code>
       * @return Whether the message field is set.
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }

      private tech.ydb.YdbIssueMessage.IssueMessage.Position endPosition_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ydb.YdbIssueMessage.IssueMessage.Position, tech.ydb.YdbIssueMessage.IssueMessage.Position.Builder, tech.ydb.YdbIssueMessage.IssueMessage.PositionOrBuilder> endPositionBuilder_;
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position end_position = 3;</code>
       * @return Whether the endPosition field is set.
       */
      public boolean hasEndPosition() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position end_position = 3;</code>
       * @return The endPosition.
       */
      public tech.ydb.YdbIssueMessage.IssueMessage.Position getEndPosition() {
        if (endPositionBuilder_ == null) {
          return endPosition_ == null ? tech.ydb.YdbIssueMessage.IssueMessage.Position.getDefaultInstance() : endPosition_;
        } else {
          return endPositionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position end_position = 3;</code>
       */
      public Builder setEndPosition(tech.ydb.YdbIssueMessage.IssueMessage.Position value) {
        if (endPositionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          endPosition_ = value;
          onChanged();
        } else {
          endPositionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position end_position = 3;</code>
       */
      public Builder setEndPosition(
          tech.ydb.YdbIssueMessage.IssueMessage.Position.Builder builderForValue) {
        if (endPositionBuilder_ == null) {
          endPosition_ = builderForValue.build();
          onChanged();
        } else {
          endPositionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position end_position = 3;</code>
       */
      public Builder mergeEndPosition(tech.ydb.YdbIssueMessage.IssueMessage.Position value) {
        if (endPositionBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              endPosition_ != null &&
              endPosition_ != tech.ydb.YdbIssueMessage.IssueMessage.Position.getDefaultInstance()) {
            endPosition_ =
              tech.ydb.YdbIssueMessage.IssueMessage.Position.newBuilder(endPosition_).mergeFrom(value).buildPartial();
          } else {
            endPosition_ = value;
          }
          onChanged();
        } else {
          endPositionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position end_position = 3;</code>
       */
      public Builder clearEndPosition() {
        if (endPositionBuilder_ == null) {
          endPosition_ = null;
          onChanged();
        } else {
          endPositionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position end_position = 3;</code>
       */
      public tech.ydb.YdbIssueMessage.IssueMessage.Position.Builder getEndPositionBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getEndPositionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position end_position = 3;</code>
       */
      public tech.ydb.YdbIssueMessage.IssueMessage.PositionOrBuilder getEndPositionOrBuilder() {
        if (endPositionBuilder_ != null) {
          return endPositionBuilder_.getMessageOrBuilder();
        } else {
          return endPosition_ == null ?
              tech.ydb.YdbIssueMessage.IssueMessage.Position.getDefaultInstance() : endPosition_;
        }
      }
      /**
       * <code>optional .Ydb.Issue.IssueMessage.Position end_position = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tech.ydb.YdbIssueMessage.IssueMessage.Position, tech.ydb.YdbIssueMessage.IssueMessage.Position.Builder, tech.ydb.YdbIssueMessage.IssueMessage.PositionOrBuilder> 
          getEndPositionFieldBuilder() {
        if (endPositionBuilder_ == null) {
          endPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tech.ydb.YdbIssueMessage.IssueMessage.Position, tech.ydb.YdbIssueMessage.IssueMessage.Position.Builder, tech.ydb.YdbIssueMessage.IssueMessage.PositionOrBuilder>(
                  getEndPosition(),
                  getParentForChildren(),
                  isClean());
          endPosition_ = null;
        }
        return endPositionBuilder_;
      }

      private int issueCode_ ;
      /**
       * <code>optional uint32 issue_code = 4;</code>
       * @return Whether the issueCode field is set.
       */
      @java.lang.Override
      public boolean hasIssueCode() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint32 issue_code = 4;</code>
       * @return The issueCode.
       */
      @java.lang.Override
      public int getIssueCode() {
        return issueCode_;
      }
      /**
       * <code>optional uint32 issue_code = 4;</code>
       * @param value The issueCode to set.
       * @return This builder for chaining.
       */
      public Builder setIssueCode(int value) {
        bitField0_ |= 0x00000008;
        issueCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 issue_code = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIssueCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        issueCode_ = 0;
        onChanged();
        return this;
      }

      private int severity_ ;
      /**
       * <pre>
       * Severity values from yql/public/issue/protos/issue_severity.proto
       * FATAL = 0;
       * ERROR = 1;
       * WARNING = 2;
       * INFO = 3;
       * </pre>
       *
       * <code>optional uint32 severity = 5;</code>
       * @return Whether the severity field is set.
       */
      @java.lang.Override
      public boolean hasSeverity() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * Severity values from yql/public/issue/protos/issue_severity.proto
       * FATAL = 0;
       * ERROR = 1;
       * WARNING = 2;
       * INFO = 3;
       * </pre>
       *
       * <code>optional uint32 severity = 5;</code>
       * @return The severity.
       */
      @java.lang.Override
      public int getSeverity() {
        return severity_;
      }
      /**
       * <pre>
       * Severity values from yql/public/issue/protos/issue_severity.proto
       * FATAL = 0;
       * ERROR = 1;
       * WARNING = 2;
       * INFO = 3;
       * </pre>
       *
       * <code>optional uint32 severity = 5;</code>
       * @param value The severity to set.
       * @return This builder for chaining.
       */
      public Builder setSeverity(int value) {
        bitField0_ |= 0x00000010;
        severity_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Severity values from yql/public/issue/protos/issue_severity.proto
       * FATAL = 0;
       * ERROR = 1;
       * WARNING = 2;
       * INFO = 3;
       * </pre>
       *
       * <code>optional uint32 severity = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeverity() {
        bitField0_ = (bitField0_ & ~0x00000010);
        severity_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<tech.ydb.YdbIssueMessage.IssueMessage> issues_ =
        java.util.Collections.emptyList();
      private void ensureIssuesIsMutable() {
        if (!((bitField0_ & 0x00000020) != 0)) {
          issues_ = new java.util.ArrayList<tech.ydb.YdbIssueMessage.IssueMessage>(issues_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          tech.ydb.YdbIssueMessage.IssueMessage, tech.ydb.YdbIssueMessage.IssueMessage.Builder, tech.ydb.YdbIssueMessage.IssueMessageOrBuilder> issuesBuilder_;

      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public java.util.List<tech.ydb.YdbIssueMessage.IssueMessage> getIssuesList() {
        if (issuesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(issues_);
        } else {
          return issuesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public int getIssuesCount() {
        if (issuesBuilder_ == null) {
          return issues_.size();
        } else {
          return issuesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public tech.ydb.YdbIssueMessage.IssueMessage getIssues(int index) {
        if (issuesBuilder_ == null) {
          return issues_.get(index);
        } else {
          return issuesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public Builder setIssues(
          int index, tech.ydb.YdbIssueMessage.IssueMessage value) {
        if (issuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIssuesIsMutable();
          issues_.set(index, value);
          onChanged();
        } else {
          issuesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public Builder setIssues(
          int index, tech.ydb.YdbIssueMessage.IssueMessage.Builder builderForValue) {
        if (issuesBuilder_ == null) {
          ensureIssuesIsMutable();
          issues_.set(index, builderForValue.build());
          onChanged();
        } else {
          issuesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public Builder addIssues(tech.ydb.YdbIssueMessage.IssueMessage value) {
        if (issuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIssuesIsMutable();
          issues_.add(value);
          onChanged();
        } else {
          issuesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public Builder addIssues(
          int index, tech.ydb.YdbIssueMessage.IssueMessage value) {
        if (issuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIssuesIsMutable();
          issues_.add(index, value);
          onChanged();
        } else {
          issuesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public Builder addIssues(
          tech.ydb.YdbIssueMessage.IssueMessage.Builder builderForValue) {
        if (issuesBuilder_ == null) {
          ensureIssuesIsMutable();
          issues_.add(builderForValue.build());
          onChanged();
        } else {
          issuesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public Builder addIssues(
          int index, tech.ydb.YdbIssueMessage.IssueMessage.Builder builderForValue) {
        if (issuesBuilder_ == null) {
          ensureIssuesIsMutable();
          issues_.add(index, builderForValue.build());
          onChanged();
        } else {
          issuesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public Builder addAllIssues(
          java.lang.Iterable<? extends tech.ydb.YdbIssueMessage.IssueMessage> values) {
        if (issuesBuilder_ == null) {
          ensureIssuesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, issues_);
          onChanged();
        } else {
          issuesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public Builder clearIssues() {
        if (issuesBuilder_ == null) {
          issues_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          issuesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public Builder removeIssues(int index) {
        if (issuesBuilder_ == null) {
          ensureIssuesIsMutable();
          issues_.remove(index);
          onChanged();
        } else {
          issuesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public tech.ydb.YdbIssueMessage.IssueMessage.Builder getIssuesBuilder(
          int index) {
        return getIssuesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public tech.ydb.YdbIssueMessage.IssueMessageOrBuilder getIssuesOrBuilder(
          int index) {
        if (issuesBuilder_ == null) {
          return issues_.get(index);  } else {
          return issuesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public java.util.List<? extends tech.ydb.YdbIssueMessage.IssueMessageOrBuilder> 
           getIssuesOrBuilderList() {
        if (issuesBuilder_ != null) {
          return issuesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(issues_);
        }
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public tech.ydb.YdbIssueMessage.IssueMessage.Builder addIssuesBuilder() {
        return getIssuesFieldBuilder().addBuilder(
            tech.ydb.YdbIssueMessage.IssueMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public tech.ydb.YdbIssueMessage.IssueMessage.Builder addIssuesBuilder(
          int index) {
        return getIssuesFieldBuilder().addBuilder(
            index, tech.ydb.YdbIssueMessage.IssueMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .Ydb.Issue.IssueMessage issues = 6;</code>
       */
      public java.util.List<tech.ydb.YdbIssueMessage.IssueMessage.Builder> 
           getIssuesBuilderList() {
        return getIssuesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          tech.ydb.YdbIssueMessage.IssueMessage, tech.ydb.YdbIssueMessage.IssueMessage.Builder, tech.ydb.YdbIssueMessage.IssueMessageOrBuilder> 
          getIssuesFieldBuilder() {
        if (issuesBuilder_ == null) {
          issuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              tech.ydb.YdbIssueMessage.IssueMessage, tech.ydb.YdbIssueMessage.IssueMessage.Builder, tech.ydb.YdbIssueMessage.IssueMessageOrBuilder>(
                  issues_,
                  ((bitField0_ & 0x00000020) != 0),
                  getParentForChildren(),
                  isClean());
          issues_ = null;
        }
        return issuesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Ydb.Issue.IssueMessage)
    }

    // @@protoc_insertion_point(class_scope:Ydb.Issue.IssueMessage)
    private static final tech.ydb.YdbIssueMessage.IssueMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tech.ydb.YdbIssueMessage.IssueMessage();
    }

    public static tech.ydb.YdbIssueMessage.IssueMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<IssueMessage>
        PARSER = new com.google.protobuf.AbstractParser<IssueMessage>() {
      @java.lang.Override
      public IssueMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IssueMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IssueMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IssueMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tech.ydb.YdbIssueMessage.IssueMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ydb_Issue_IssueMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ydb_Issue_IssueMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ydb_Issue_IssueMessage_Position_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ydb_Issue_IssueMessage_Position_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0kikimr/public/api/protos/ydb_issue_mes" +
      "sage.proto\022\tYdb.Issue\"\221\002\n\014IssueMessage\0222" +
      "\n\010position\030\001 \001(\0132 .Ydb.Issue.IssueMessag" +
      "e.Position\022\017\n\007message\030\002 \001(\t\0226\n\014end_posit" +
      "ion\030\003 \001(\0132 .Ydb.Issue.IssueMessage.Posit" +
      "ion\022\022\n\nissue_code\030\004 \001(\r\022\020\n\010severity\030\005 \001(" +
      "\r\022\'\n\006issues\030\006 \003(\0132\027.Ydb.Issue.IssueMessa" +
      "ge\0325\n\010Position\022\013\n\003row\030\001 \001(\r\022\016\n\006column\030\002 " +
      "\001(\r\022\014\n\004file\030\003 \001(\tB\020\n\016tech.ydb"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Ydb_Issue_IssueMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Ydb_Issue_IssueMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ydb_Issue_IssueMessage_descriptor,
        new java.lang.String[] { "Position", "Message", "EndPosition", "IssueCode", "Severity", "Issues", });
    internal_static_Ydb_Issue_IssueMessage_Position_descriptor =
      internal_static_Ydb_Issue_IssueMessage_descriptor.getNestedTypes().get(0);
    internal_static_Ydb_Issue_IssueMessage_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ydb_Issue_IssueMessage_Position_descriptor,
        new java.lang.String[] { "Row", "Column", "File", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
