// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kikimr/public/api/grpc/ydb_rate_limiter_v1.proto

package tech.ydb.rate_limiter.v1;

public final class RateLimiterGrpc {
  private RateLimiterGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0kikimr/public/api/grpc/ydb_rate_limite" +
      "r_v1.proto\022\022Ydb.RateLimiter.V1\032/kikimr/p" +
      "ublic/api/protos/ydb_rate_limiter.proto2" +
      "\343\004\n\022RateLimiterService\022a\n\016CreateResource" +
      "\022&.Ydb.RateLimiter.CreateResourceRequest" +
      "\032\'.Ydb.RateLimiter.CreateResourceRespons" +
      "e\022^\n\rAlterResource\022%.Ydb.RateLimiter.Alt" +
      "erResourceRequest\032&.Ydb.RateLimiter.Alte" +
      "rResourceResponse\022[\n\014DropResource\022$.Ydb." +
      "RateLimiter.DropResourceRequest\032%.Ydb.Ra",
      "teLimiter.DropResourceResponse\022^\n\rListRe" +
      "sources\022%.Ydb.RateLimiter.ListResourcesR" +
      "equest\032&.Ydb.RateLimiter.ListResourcesRe" +
      "sponse\022g\n\020DescribeResource\022(.Ydb.RateLim" +
      "iter.DescribeResourceRequest\032).Ydb.RateL" +
      "imiter.DescribeResourceResponse\022d\n\017Acqui" +
      "reResource\022\'.Ydb.RateLimiter.AcquireReso" +
      "urceRequest\032(.Ydb.RateLimiter.AcquireRes" +
      "ourceResponseB3\n\036tech.ydb.rate_lim" +
      "iter.v1B\017RateLimiterGrpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tech.ydb.rate_limiter.RateLimiterProtos.getDescriptor(),
        }, assigner);
    tech.ydb.rate_limiter.RateLimiterProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
