// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kikimr/public/api/grpc/draft/ydb_clickhouse_internal_v1.proto

package tech.ydb.clickhouse.v1;

public final class YdbClickhouseInternalV1 {
  private YdbClickhouseInternalV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=kikimr/public/api/grpc/draft/ydb_click" +
      "house_internal_v1.proto\022\031Ydb.ClickhouseI" +
      "nternal.V1\0326kikimr/public/api/protos/ydb" +
      "_clickhouse_internal.proto2\326\002\n\031Clickhous" +
      "eInternalService\022Q\n\004Scan\022#.Ydb.Clickhous" +
      "eInternal.ScanRequest\032$.Ydb.ClickhouseIn" +
      "ternal.ScanResponse\022x\n\021GetShardLocations" +
      "\0220.Ydb.ClickhouseInternal.GetShardLocati" +
      "onsRequest\0321.Ydb.ClickhouseInternal.GetS" +
      "hardLocationsResponse\022l\n\rDescribeTable\022,",
      ".Ydb.ClickhouseInternal.DescribeTableReq" +
      "uest\032-.Ydb.ClickhouseInternal.DescribeTa" +
      "bleResponseB\036\n\034tech.ydb.clickhouse" +
      ".v1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tech.ydb.clickhouse.ClickhouseInternalProtos.getDescriptor(),
        }, assigner);
    tech.ydb.clickhouse.ClickhouseInternalProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
