// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kikimr/public/api/grpc/draft/yq_v1.proto

package com.yandex.query.v1;

public final class YqV1 {
  private YqV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(kikimr/public/api/grpc/draft/yq_v1.pro" +
      "to\022\016YandexQuery.V1\032\'kikimr/public/api/pr" +
      "otos/draft/yq.proto2\277\r\n\022YandexQueryServi" +
      "ce\022_\n\020ExecuteOperation\022$.YandexQuery.Exe" +
      "cuteOperationRequest\032%.YandexQuery.Execu" +
      "teOperationResponse\022Y\n\016ListOperations\022\"." +
      "YandexQuery.ListOperationsRequest\032#.Yand" +
      "exQuery.ListOperationsResponse\022b\n\021Descri" +
      "beOperation\022%.YandexQuery.DescribeOperat" +
      "ionRequest\032&.YandexQuery.DescribeOperati",
      "onResponse\022t\n\027DescribeOperationResult\022+." +
      "YandexQuery.DescribeOperationResultReque" +
      "st\032,.YandexQuery.DescribeOperationResult" +
      "Response\022\\\n\017ModifyOperation\022#.YandexQuer" +
      "y.ModifyOperationRequest\032$.YandexQuery.M" +
      "odifyOperationResponse\022\\\n\017DeleteOperatio" +
      "n\022#.YandexQuery.DeleteOperationRequest\032$" +
      ".YandexQuery.DeleteOperationResponse\022\\\n\017" +
      "ManageOperation\022#.YandexQuery.ManageOper" +
      "ationRequest\032$.YandexQuery.ManageOperati",
      "onResponse\022V\n\rGetResultData\022!.YandexQuer" +
      "y.GetResultDataRequest\032\".YandexQuery.Get" +
      "ResultDataResponse\022_\n\020CreateConnection\022$" +
      ".YandexQuery.CreateConnectionRequest\032%.Y" +
      "andexQuery.CreateConnectionResponse\022\\\n\017L" +
      "istConnections\022#.YandexQuery.ListConnect" +
      "ionsRequest\032$.YandexQuery.ListConnection" +
      "sResponse\022e\n\022DescribeConnection\022&.Yandex" +
      "Query.DescribeConnectionRequest\032\'.Yandex" +
      "Query.DescribeConnectionResponse\022_\n\020Modi",
      "fyConnection\022$.YandexQuery.ModifyConnect" +
      "ionRequest\032%.YandexQuery.ModifyConnectio" +
      "nResponse\022_\n\020DeleteConnection\022$.YandexQu" +
      "ery.DeleteConnectionRequest\032%.YandexQuer" +
      "y.DeleteConnectionResponse\022V\n\rCreateBind" +
      "ing\022!.YandexQuery.CreateBindingRequest\032\"" +
      ".YandexQuery.CreateBindingResponse\022S\n\014Li" +
      "stBindings\022 .YandexQuery.ListBindingsReq" +
      "uest\032!.YandexQuery.ListBindingsResponse\022" +
      "\\\n\017DescribeBinding\022#.YandexQuery.Describ",
      "eBindingRequest\032$.YandexQuery.DescribeBi" +
      "ndingResponse\022V\n\rModifyBinding\022!.YandexQ" +
      "uery.ModifyBindingRequest\032\".YandexQuery." +
      "ModifyBindingResponse\022V\n\rDeleteBinding\022!" +
      ".YandexQuery.DeleteBindingRequest\032\".Yand" +
      "exQuery.DeleteBindingResponseB\025\n\023com.yan" +
      "dex.query.v1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yandex.query.YandexQueryProtos.getDescriptor(),
        }, assigner);
    com.yandex.query.YandexQueryProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
