// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kikimr/public/api/protos/ydb_coordination.proto

package tech.ydb.coordination;

public interface CreateNodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ydb.Coordination.CreateNodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 1;</code>
   */
  java.lang.String getPath();
  /**
   * <code>string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>.Ydb.Coordination.Config config = 2;</code>
   */
  boolean hasConfig();
  /**
   * <code>.Ydb.Coordination.Config config = 2;</code>
   */
  tech.ydb.coordination.Config getConfig();
  /**
   * <code>.Ydb.Coordination.Config config = 2;</code>
   */
  tech.ydb.coordination.ConfigOrBuilder getConfigOrBuilder();

  /**
   * <code>.Ydb.Operations.OperationParams operation_params = 3;</code>
   */
  boolean hasOperationParams();
  /**
   * <code>.Ydb.Operations.OperationParams operation_params = 3;</code>
   */
  tech.ydb.OperationProtos.OperationParams getOperationParams();
  /**
   * <code>.Ydb.Operations.OperationParams operation_params = 3;</code>
   */
  tech.ydb.OperationProtos.OperationParamsOrBuilder getOperationParamsOrBuilder();
}
