// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kikimr/public/api/protos/ydb_coordination.proto

package tech.ydb.coordination;

public interface SessionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ydb.Coordination.SessionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Ydb.Coordination.SessionResponse.PingPong ping = 1;</code>
   */
  boolean hasPing();
  /**
   * <code>.Ydb.Coordination.SessionResponse.PingPong ping = 1;</code>
   */
  tech.ydb.coordination.SessionResponse.PingPong getPing();
  /**
   * <code>.Ydb.Coordination.SessionResponse.PingPong ping = 1;</code>
   */
  tech.ydb.coordination.SessionResponse.PingPongOrBuilder getPingOrBuilder();

  /**
   * <code>.Ydb.Coordination.SessionResponse.PingPong pong = 2;</code>
   */
  boolean hasPong();
  /**
   * <code>.Ydb.Coordination.SessionResponse.PingPong pong = 2;</code>
   */
  tech.ydb.coordination.SessionResponse.PingPong getPong();
  /**
   * <code>.Ydb.Coordination.SessionResponse.PingPong pong = 2;</code>
   */
  tech.ydb.coordination.SessionResponse.PingPongOrBuilder getPongOrBuilder();

  /**
   * <code>.Ydb.Coordination.SessionResponse.Failure failure = 3;</code>
   */
  boolean hasFailure();
  /**
   * <code>.Ydb.Coordination.SessionResponse.Failure failure = 3;</code>
   */
  tech.ydb.coordination.SessionResponse.Failure getFailure();
  /**
   * <code>.Ydb.Coordination.SessionResponse.Failure failure = 3;</code>
   */
  tech.ydb.coordination.SessionResponse.FailureOrBuilder getFailureOrBuilder();

  /**
   * <code>.Ydb.Coordination.SessionResponse.SessionStarted session_started = 4;</code>
   */
  boolean hasSessionStarted();
  /**
   * <code>.Ydb.Coordination.SessionResponse.SessionStarted session_started = 4;</code>
   */
  tech.ydb.coordination.SessionResponse.SessionStarted getSessionStarted();
  /**
   * <code>.Ydb.Coordination.SessionResponse.SessionStarted session_started = 4;</code>
   */
  tech.ydb.coordination.SessionResponse.SessionStartedOrBuilder getSessionStartedOrBuilder();

  /**
   * <code>.Ydb.Coordination.SessionResponse.SessionStopped session_stopped = 5;</code>
   */
  boolean hasSessionStopped();
  /**
   * <code>.Ydb.Coordination.SessionResponse.SessionStopped session_stopped = 5;</code>
   */
  tech.ydb.coordination.SessionResponse.SessionStopped getSessionStopped();
  /**
   * <code>.Ydb.Coordination.SessionResponse.SessionStopped session_stopped = 5;</code>
   */
  tech.ydb.coordination.SessionResponse.SessionStoppedOrBuilder getSessionStoppedOrBuilder();

  /**
   * <code>.Ydb.Coordination.Unsupported unsupported_6 = 6;</code>
   */
  boolean hasUnsupported6();
  /**
   * <code>.Ydb.Coordination.Unsupported unsupported_6 = 6;</code>
   */
  tech.ydb.coordination.Unsupported getUnsupported6();
  /**
   * <code>.Ydb.Coordination.Unsupported unsupported_6 = 6;</code>
   */
  tech.ydb.coordination.UnsupportedOrBuilder getUnsupported6OrBuilder();

  /**
   * <code>.Ydb.Coordination.Unsupported unsupported_7 = 7;</code>
   */
  boolean hasUnsupported7();
  /**
   * <code>.Ydb.Coordination.Unsupported unsupported_7 = 7;</code>
   */
  tech.ydb.coordination.Unsupported getUnsupported7();
  /**
   * <code>.Ydb.Coordination.Unsupported unsupported_7 = 7;</code>
   */
  tech.ydb.coordination.UnsupportedOrBuilder getUnsupported7OrBuilder();

  /**
   * <code>.Ydb.Coordination.SessionResponse.AcquireSemaphorePending acquire_semaphore_pending = 8;</code>
   */
  boolean hasAcquireSemaphorePending();
  /**
   * <code>.Ydb.Coordination.SessionResponse.AcquireSemaphorePending acquire_semaphore_pending = 8;</code>
   */
  tech.ydb.coordination.SessionResponse.AcquireSemaphorePending getAcquireSemaphorePending();
  /**
   * <code>.Ydb.Coordination.SessionResponse.AcquireSemaphorePending acquire_semaphore_pending = 8;</code>
   */
  tech.ydb.coordination.SessionResponse.AcquireSemaphorePendingOrBuilder getAcquireSemaphorePendingOrBuilder();

  /**
   * <code>.Ydb.Coordination.SessionResponse.AcquireSemaphoreResult acquire_semaphore_result = 9;</code>
   */
  boolean hasAcquireSemaphoreResult();
  /**
   * <code>.Ydb.Coordination.SessionResponse.AcquireSemaphoreResult acquire_semaphore_result = 9;</code>
   */
  tech.ydb.coordination.SessionResponse.AcquireSemaphoreResult getAcquireSemaphoreResult();
  /**
   * <code>.Ydb.Coordination.SessionResponse.AcquireSemaphoreResult acquire_semaphore_result = 9;</code>
   */
  tech.ydb.coordination.SessionResponse.AcquireSemaphoreResultOrBuilder getAcquireSemaphoreResultOrBuilder();

  /**
   * <code>.Ydb.Coordination.SessionResponse.ReleaseSemaphoreResult release_semaphore_result = 10;</code>
   */
  boolean hasReleaseSemaphoreResult();
  /**
   * <code>.Ydb.Coordination.SessionResponse.ReleaseSemaphoreResult release_semaphore_result = 10;</code>
   */
  tech.ydb.coordination.SessionResponse.ReleaseSemaphoreResult getReleaseSemaphoreResult();
  /**
   * <code>.Ydb.Coordination.SessionResponse.ReleaseSemaphoreResult release_semaphore_result = 10;</code>
   */
  tech.ydb.coordination.SessionResponse.ReleaseSemaphoreResultOrBuilder getReleaseSemaphoreResultOrBuilder();

  /**
   * <code>.Ydb.Coordination.SessionResponse.DescribeSemaphoreResult describe_semaphore_result = 11;</code>
   */
  boolean hasDescribeSemaphoreResult();
  /**
   * <code>.Ydb.Coordination.SessionResponse.DescribeSemaphoreResult describe_semaphore_result = 11;</code>
   */
  tech.ydb.coordination.SessionResponse.DescribeSemaphoreResult getDescribeSemaphoreResult();
  /**
   * <code>.Ydb.Coordination.SessionResponse.DescribeSemaphoreResult describe_semaphore_result = 11;</code>
   */
  tech.ydb.coordination.SessionResponse.DescribeSemaphoreResultOrBuilder getDescribeSemaphoreResultOrBuilder();

  /**
   * <code>.Ydb.Coordination.SessionResponse.DescribeSemaphoreChanged describe_semaphore_changed = 12;</code>
   */
  boolean hasDescribeSemaphoreChanged();
  /**
   * <code>.Ydb.Coordination.SessionResponse.DescribeSemaphoreChanged describe_semaphore_changed = 12;</code>
   */
  tech.ydb.coordination.SessionResponse.DescribeSemaphoreChanged getDescribeSemaphoreChanged();
  /**
   * <code>.Ydb.Coordination.SessionResponse.DescribeSemaphoreChanged describe_semaphore_changed = 12;</code>
   */
  tech.ydb.coordination.SessionResponse.DescribeSemaphoreChangedOrBuilder getDescribeSemaphoreChangedOrBuilder();

  /**
   * <code>.Ydb.Coordination.SessionResponse.CreateSemaphoreResult create_semaphore_result = 13;</code>
   */
  boolean hasCreateSemaphoreResult();
  /**
   * <code>.Ydb.Coordination.SessionResponse.CreateSemaphoreResult create_semaphore_result = 13;</code>
   */
  tech.ydb.coordination.SessionResponse.CreateSemaphoreResult getCreateSemaphoreResult();
  /**
   * <code>.Ydb.Coordination.SessionResponse.CreateSemaphoreResult create_semaphore_result = 13;</code>
   */
  tech.ydb.coordination.SessionResponse.CreateSemaphoreResultOrBuilder getCreateSemaphoreResultOrBuilder();

  /**
   * <code>.Ydb.Coordination.SessionResponse.UpdateSemaphoreResult update_semaphore_result = 14;</code>
   */
  boolean hasUpdateSemaphoreResult();
  /**
   * <code>.Ydb.Coordination.SessionResponse.UpdateSemaphoreResult update_semaphore_result = 14;</code>
   */
  tech.ydb.coordination.SessionResponse.UpdateSemaphoreResult getUpdateSemaphoreResult();
  /**
   * <code>.Ydb.Coordination.SessionResponse.UpdateSemaphoreResult update_semaphore_result = 14;</code>
   */
  tech.ydb.coordination.SessionResponse.UpdateSemaphoreResultOrBuilder getUpdateSemaphoreResultOrBuilder();

  /**
   * <code>.Ydb.Coordination.SessionResponse.DeleteSemaphoreResult delete_semaphore_result = 15;</code>
   */
  boolean hasDeleteSemaphoreResult();
  /**
   * <code>.Ydb.Coordination.SessionResponse.DeleteSemaphoreResult delete_semaphore_result = 15;</code>
   */
  tech.ydb.coordination.SessionResponse.DeleteSemaphoreResult getDeleteSemaphoreResult();
  /**
   * <code>.Ydb.Coordination.SessionResponse.DeleteSemaphoreResult delete_semaphore_result = 15;</code>
   */
  tech.ydb.coordination.SessionResponse.DeleteSemaphoreResultOrBuilder getDeleteSemaphoreResultOrBuilder();

  /**
   * <code>.Ydb.Coordination.Unsupported unsupported_16 = 16;</code>
   */
  boolean hasUnsupported16();
  /**
   * <code>.Ydb.Coordination.Unsupported unsupported_16 = 16;</code>
   */
  tech.ydb.coordination.Unsupported getUnsupported16();
  /**
   * <code>.Ydb.Coordination.Unsupported unsupported_16 = 16;</code>
   */
  tech.ydb.coordination.UnsupportedOrBuilder getUnsupported16OrBuilder();

  /**
   * <code>.Ydb.Coordination.Unsupported unsupported_17 = 17;</code>
   */
  boolean hasUnsupported17();
  /**
   * <code>.Ydb.Coordination.Unsupported unsupported_17 = 17;</code>
   */
  tech.ydb.coordination.Unsupported getUnsupported17();
  /**
   * <code>.Ydb.Coordination.Unsupported unsupported_17 = 17;</code>
   */
  tech.ydb.coordination.UnsupportedOrBuilder getUnsupported17OrBuilder();

  /**
   * <code>.Ydb.Coordination.Unsupported unsupported_18 = 18;</code>
   */
  boolean hasUnsupported18();
  /**
   * <code>.Ydb.Coordination.Unsupported unsupported_18 = 18;</code>
   */
  tech.ydb.coordination.Unsupported getUnsupported18();
  /**
   * <code>.Ydb.Coordination.Unsupported unsupported_18 = 18;</code>
   */
  tech.ydb.coordination.UnsupportedOrBuilder getUnsupported18OrBuilder();

  public tech.ydb.coordination.SessionResponse.ResponseCase getResponseCase();
}
