// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kikimr/public/api/grpc/draft/ydb_long_tx_v1.proto

package tech.ydb.long_tx.v1;

public final class YdbLongTxV1 {
  private YdbLongTxV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1kikimr/public/api/grpc/draft/ydb_long_" +
      "tx_v1.proto\022\rYdb.LongTx.V1\0320kikimr/publi" +
      "c/api/protos/draft/ydb_long_tx.proto2\226\003\n" +
      "\rLongTxService\022T\n\007BeginTx\022#.Ydb.LongTx.B" +
      "eginTransactionRequest\032$.Ydb.LongTx.Begi" +
      "nTransactionResponse\022W\n\010CommitTx\022$.Ydb.L" +
      "ongTx.CommitTransactionRequest\032%.Ydb.Lon" +
      "gTx.CommitTransactionResponse\022]\n\nRollbac" +
      "kTx\022&.Ydb.LongTx.RollbackTransactionRequ" +
      "est\032\'.Ydb.LongTx.RollbackTransactionResp",
      "onse\022<\n\005Write\022\030.Ydb.LongTx.WriteRequest\032" +
      "\031.Ydb.LongTx.WriteResponse\0229\n\004Read\022\027.Ydb" +
      ".LongTx.ReadRequest\032\030.Ydb.LongTx.ReadRes" +
      "ponseB\033\n\031tech.ydb.long_tx.v1b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tech.ydb.long_tx.LongTxProtos.getDescriptor(),
        }, assigner);
    tech.ydb.long_tx.LongTxProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
