// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ydb/public/api/grpc/ydb_table_v1.proto

package tech.ydb.table.v1;

public final class YdbTableV1 {
  private YdbTableV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&ydb/public/api/grpc/ydb_table_v1.proto" +
      "\022\014Ydb.Table.V1\032%ydb/public/api/protos/yd" +
      "b_table.proto2\244\016\n\014TableService\022R\n\rCreate" +
      "Session\022\037.Ydb.Table.CreateSessionRequest" +
      "\032 .Ydb.Table.CreateSessionResponse\022R\n\rDe" +
      "leteSession\022\037.Ydb.Table.DeleteSessionReq" +
      "uest\032 .Ydb.Table.DeleteSessionResponse\022F" +
      "\n\tKeepAlive\022\033.Ydb.Table.KeepAliveRequest" +
      "\032\034.Ydb.Table.KeepAliveResponse\022L\n\013Create" +
      "Table\022\035.Ydb.Table.CreateTableRequest\032\036.Y" +
      "db.Table.CreateTableResponse\022F\n\tDropTabl" +
      "e\022\033.Ydb.Table.DropTableRequest\032\034.Ydb.Tab" +
      "le.DropTableResponse\022I\n\nAlterTable\022\034.Ydb" +
      ".Table.AlterTableRequest\032\035.Ydb.Table.Alt" +
      "erTableResponse\022F\n\tCopyTable\022\033.Ydb.Table" +
      ".CopyTableRequest\032\034.Ydb.Table.CopyTableR" +
      "esponse\022I\n\nCopyTables\022\034.Ydb.Table.CopyTa" +
      "blesRequest\032\035.Ydb.Table.CopyTablesRespon" +
      "se\022O\n\014RenameTables\022\036.Ydb.Table.RenameTab" +
      "lesRequest\032\037.Ydb.Table.RenameTablesRespo" +
      "nse\022R\n\rDescribeTable\022\037.Ydb.Table.Describ" +
      "eTableRequest\032 .Ydb.Table.DescribeTableR" +
      "esponse\022[\n\020ExplainDataQuery\022\".Ydb.Table." +
      "ExplainDataQueryRequest\032#.Ydb.Table.Expl" +
      "ainDataQueryResponse\022[\n\020PrepareDataQuery" +
      "\022\".Ydb.Table.PrepareDataQueryRequest\032#.Y" +
      "db.Table.PrepareDataQueryResponse\022[\n\020Exe" +
      "cuteDataQuery\022\".Ydb.Table.ExecuteDataQue" +
      "ryRequest\032#.Ydb.Table.ExecuteDataQueryRe" +
      "sponse\022a\n\022ExecuteSchemeQuery\022$.Ydb.Table" +
      ".ExecuteSchemeQueryRequest\032%.Ydb.Table.E" +
      "xecuteSchemeQueryResponse\022[\n\020BeginTransa" +
      "ction\022\".Ydb.Table.BeginTransactionReques" +
      "t\032#.Ydb.Table.BeginTransactionResponse\022^" +
      "\n\021CommitTransaction\022#.Ydb.Table.CommitTr" +
      "ansactionRequest\032$.Ydb.Table.CommitTrans" +
      "actionResponse\022d\n\023RollbackTransaction\022%." +
      "Ydb.Table.RollbackTransactionRequest\032&.Y" +
      "db.Table.RollbackTransactionResponse\022g\n\024" +
      "DescribeTableOptions\022&.Ydb.Table.Describ" +
      "eTableOptionsRequest\032\'.Ydb.Table.Describ" +
      "eTableOptionsResponse\022N\n\017StreamReadTable" +
      "\022\033.Ydb.Table.ReadTableRequest\032\034.Ydb.Tabl" +
      "e.ReadTableResponse0\001\022I\n\nBulkUpsert\022\034.Yd" +
      "b.Table.BulkUpsertRequest\032\035.Ydb.Table.Bu" +
      "lkUpsertResponse\022j\n\026StreamExecuteScanQue" +
      "ry\022\".Ydb.Table.ExecuteScanQueryRequest\032*" +
      ".Ydb.Table.ExecuteScanQueryPartialRespon" +
      "se0\001B\031\n\027tech.ydb.table.v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tech.ydb.table.YdbTable.getDescriptor(),
        });
    tech.ydb.table.YdbTable.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
