// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kikimr/public/api/protos/ydb_rate_limiter.proto

package tech.ydb.rate_limiter;

public interface AcquireResourceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ydb.RateLimiter.AcquireResourceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
   * @return Whether the operationParams field is set.
   */
  boolean hasOperationParams();
  /**
   * <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
   * @return The operationParams.
   */
  tech.ydb.OperationProtos.OperationParams getOperationParams();
  /**
   * <code>.Ydb.Operations.OperationParams operation_params = 1;</code>
   */
  tech.ydb.OperationProtos.OperationParamsOrBuilder getOperationParamsOrBuilder();

  /**
   * <pre>
   * Path of a coordination node.
   * </pre>
   *
   * <code>string coordination_node_path = 2;</code>
   * @return The coordinationNodePath.
   */
  java.lang.String getCoordinationNodePath();
  /**
   * <pre>
   * Path of a coordination node.
   * </pre>
   *
   * <code>string coordination_node_path = 2;</code>
   * @return The bytes for coordinationNodePath.
   */
  com.google.protobuf.ByteString
      getCoordinationNodePathBytes();

  /**
   * <pre>
   * Path of resource inside a coordination node.
   * </pre>
   *
   * <code>string resource_path = 3;</code>
   * @return The resourcePath.
   */
  java.lang.String getResourcePath();
  /**
   * <pre>
   * Path of resource inside a coordination node.
   * </pre>
   *
   * <code>string resource_path = 3;</code>
   * @return The bytes for resourcePath.
   */
  com.google.protobuf.ByteString
      getResourcePathBytes();

  /**
   * <pre>
   * Request resource's units for usage.
   * </pre>
   *
   * <code>uint64 required = 4;</code>
   * @return Whether the required field is set.
   */
  boolean hasRequired();
  /**
   * <pre>
   * Request resource's units for usage.
   * </pre>
   *
   * <code>uint64 required = 4;</code>
   * @return The required.
   */
  long getRequired();

  /**
   * <pre>
   * Actually used resource's units by client.
   * </pre>
   *
   * <code>uint64 used = 5;</code>
   * @return Whether the used field is set.
   */
  boolean hasUsed();
  /**
   * <pre>
   * Actually used resource's units by client.
   * </pre>
   *
   * <code>uint64 used = 5;</code>
   * @return The used.
   */
  long getUsed();

  public tech.ydb.rate_limiter.AcquireResourceRequest.UnitsCase getUnitsCase();
}
