// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kikimr/public/api/protos/ydb_rate_limiter.proto

package tech.ydb.rate_limiter;

public interface AlterResourceResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ydb.RateLimiter.AlterResourceResult)
    com.google.protobuf.MessageOrBuilder {
}
