// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kikimr/public/api/protos/ydb_rate_limiter.proto

package tech.ydb.rate_limiter;

/**
 * Protobuf type {@code Ydb.RateLimiter.ListResourcesResult}
 */
public final class ListResourcesResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Ydb.RateLimiter.ListResourcesResult)
    ListResourcesResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListResourcesResult.newBuilder() to construct.
  private ListResourcesResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListResourcesResult() {
    resourcePaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListResourcesResult();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListResourcesResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              resourcePaths_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            resourcePaths_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        resourcePaths_ = resourcePaths_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tech.ydb.rate_limiter.RateLimiterProtos.internal_static_Ydb_RateLimiter_ListResourcesResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tech.ydb.rate_limiter.RateLimiterProtos.internal_static_Ydb_RateLimiter_ListResourcesResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tech.ydb.rate_limiter.ListResourcesResult.class, tech.ydb.rate_limiter.ListResourcesResult.Builder.class);
  }

  public static final int RESOURCE_PATHS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList resourcePaths_;
  /**
   * <code>repeated string resource_paths = 1;</code>
   * @return A list containing the resourcePaths.
   */
  public com.google.protobuf.ProtocolStringList
      getResourcePathsList() {
    return resourcePaths_;
  }
  /**
   * <code>repeated string resource_paths = 1;</code>
   * @return The count of resourcePaths.
   */
  public int getResourcePathsCount() {
    return resourcePaths_.size();
  }
  /**
   * <code>repeated string resource_paths = 1;</code>
   * @param index The index of the element to return.
   * @return The resourcePaths at the given index.
   */
  public java.lang.String getResourcePaths(int index) {
    return resourcePaths_.get(index);
  }
  /**
   * <code>repeated string resource_paths = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the resourcePaths at the given index.
   */
  public com.google.protobuf.ByteString
      getResourcePathsBytes(int index) {
    return resourcePaths_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < resourcePaths_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resourcePaths_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < resourcePaths_.size(); i++) {
        dataSize += computeStringSizeNoTag(resourcePaths_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getResourcePathsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tech.ydb.rate_limiter.ListResourcesResult)) {
      return super.equals(obj);
    }
    tech.ydb.rate_limiter.ListResourcesResult other = (tech.ydb.rate_limiter.ListResourcesResult) obj;

    if (!getResourcePathsList()
        .equals(other.getResourcePathsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResourcePathsCount() > 0) {
      hash = (37 * hash) + RESOURCE_PATHS_FIELD_NUMBER;
      hash = (53 * hash) + getResourcePathsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tech.ydb.rate_limiter.ListResourcesResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.ydb.rate_limiter.ListResourcesResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.ydb.rate_limiter.ListResourcesResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.ydb.rate_limiter.ListResourcesResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.ydb.rate_limiter.ListResourcesResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.ydb.rate_limiter.ListResourcesResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.ydb.rate_limiter.ListResourcesResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.ydb.rate_limiter.ListResourcesResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.ydb.rate_limiter.ListResourcesResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static tech.ydb.rate_limiter.ListResourcesResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.ydb.rate_limiter.ListResourcesResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.ydb.rate_limiter.ListResourcesResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tech.ydb.rate_limiter.ListResourcesResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Ydb.RateLimiter.ListResourcesResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Ydb.RateLimiter.ListResourcesResult)
      tech.ydb.rate_limiter.ListResourcesResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.ydb.rate_limiter.RateLimiterProtos.internal_static_Ydb_RateLimiter_ListResourcesResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.ydb.rate_limiter.RateLimiterProtos.internal_static_Ydb_RateLimiter_ListResourcesResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.ydb.rate_limiter.ListResourcesResult.class, tech.ydb.rate_limiter.ListResourcesResult.Builder.class);
    }

    // Construct using tech.ydb.rate_limiter.ListResourcesResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      resourcePaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tech.ydb.rate_limiter.RateLimiterProtos.internal_static_Ydb_RateLimiter_ListResourcesResult_descriptor;
    }

    @java.lang.Override
    public tech.ydb.rate_limiter.ListResourcesResult getDefaultInstanceForType() {
      return tech.ydb.rate_limiter.ListResourcesResult.getDefaultInstance();
    }

    @java.lang.Override
    public tech.ydb.rate_limiter.ListResourcesResult build() {
      tech.ydb.rate_limiter.ListResourcesResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tech.ydb.rate_limiter.ListResourcesResult buildPartial() {
      tech.ydb.rate_limiter.ListResourcesResult result = new tech.ydb.rate_limiter.ListResourcesResult(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        resourcePaths_ = resourcePaths_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.resourcePaths_ = resourcePaths_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tech.ydb.rate_limiter.ListResourcesResult) {
        return mergeFrom((tech.ydb.rate_limiter.ListResourcesResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tech.ydb.rate_limiter.ListResourcesResult other) {
      if (other == tech.ydb.rate_limiter.ListResourcesResult.getDefaultInstance()) return this;
      if (!other.resourcePaths_.isEmpty()) {
        if (resourcePaths_.isEmpty()) {
          resourcePaths_ = other.resourcePaths_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureResourcePathsIsMutable();
          resourcePaths_.addAll(other.resourcePaths_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      tech.ydb.rate_limiter.ListResourcesResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (tech.ydb.rate_limiter.ListResourcesResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList resourcePaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureResourcePathsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        resourcePaths_ = new com.google.protobuf.LazyStringArrayList(resourcePaths_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string resource_paths = 1;</code>
     * @return A list containing the resourcePaths.
     */
    public com.google.protobuf.ProtocolStringList
        getResourcePathsList() {
      return resourcePaths_.getUnmodifiableView();
    }
    /**
     * <code>repeated string resource_paths = 1;</code>
     * @return The count of resourcePaths.
     */
    public int getResourcePathsCount() {
      return resourcePaths_.size();
    }
    /**
     * <code>repeated string resource_paths = 1;</code>
     * @param index The index of the element to return.
     * @return The resourcePaths at the given index.
     */
    public java.lang.String getResourcePaths(int index) {
      return resourcePaths_.get(index);
    }
    /**
     * <code>repeated string resource_paths = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the resourcePaths at the given index.
     */
    public com.google.protobuf.ByteString
        getResourcePathsBytes(int index) {
      return resourcePaths_.getByteString(index);
    }
    /**
     * <code>repeated string resource_paths = 1;</code>
     * @param index The index to set the value at.
     * @param value The resourcePaths to set.
     * @return This builder for chaining.
     */
    public Builder setResourcePaths(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureResourcePathsIsMutable();
      resourcePaths_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string resource_paths = 1;</code>
     * @param value The resourcePaths to add.
     * @return This builder for chaining.
     */
    public Builder addResourcePaths(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureResourcePathsIsMutable();
      resourcePaths_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string resource_paths = 1;</code>
     * @param values The resourcePaths to add.
     * @return This builder for chaining.
     */
    public Builder addAllResourcePaths(
        java.lang.Iterable<java.lang.String> values) {
      ensureResourcePathsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, resourcePaths_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string resource_paths = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResourcePaths() {
      resourcePaths_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string resource_paths = 1;</code>
     * @param value The bytes of the resourcePaths to add.
     * @return This builder for chaining.
     */
    public Builder addResourcePathsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureResourcePathsIsMutable();
      resourcePaths_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Ydb.RateLimiter.ListResourcesResult)
  }

  // @@protoc_insertion_point(class_scope:Ydb.RateLimiter.ListResourcesResult)
  private static final tech.ydb.rate_limiter.ListResourcesResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tech.ydb.rate_limiter.ListResourcesResult();
  }

  public static tech.ydb.rate_limiter.ListResourcesResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListResourcesResult>
      PARSER = new com.google.protobuf.AbstractParser<ListResourcesResult>() {
    @java.lang.Override
    public ListResourcesResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListResourcesResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListResourcesResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListResourcesResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tech.ydb.rate_limiter.ListResourcesResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

